/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package packagefinder;

import de.troido.resigner.controll.ResignerLogic;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class MainFrame extends javax.swing.JFrame {

    
    private File inFile;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        jPanelDetailsBar.setVisible(false);
        setLocationRelativeTo(null);
        try {
			ResignerLogic.checkEnvironment();
		} catch (RuntimeException exc) {
			JOptionPane.showMessageDialog(this, exc.getMessage());
			System.exit(0);
		}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldAPKFile = new javax.swing.JTextField();
        jButtonBrowse = new javax.swing.JButton();
        jButtonGetDetails = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanelDetailsBar = new javax.swing.JPanel();
        jTextFieldPackage = new javax.swing.JTextField();
        jTextFieldMainActivity = new javax.swing.JTextField();
        jTextFieldResignedApkPath = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PackageFinder");

        jLabel1.setText("Source File :");

        jButtonBrowse.setText("Browse");
        jButtonBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseActionPerformed(evt);
            }
        });

        jButtonGetDetails.setText("Get Details");
        jButtonGetDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGetDetailsActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("APK PACKAGE FINDER");

        jPanelDetailsBar.setBorder(javax.swing.BorderFactory.createTitledBorder("Application Details"));

        jTextFieldPackage.setEditable(false);

        jTextFieldMainActivity.setEditable(false);

        jTextFieldResignedApkPath.setEditable(false);

        javax.swing.GroupLayout jPanelDetailsBarLayout = new javax.swing.GroupLayout(jPanelDetailsBar);
        jPanelDetailsBar.setLayout(jPanelDetailsBarLayout);
        jPanelDetailsBarLayout.setHorizontalGroup(
            jPanelDetailsBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetailsBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDetailsBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPackage)
                    .addComponent(jTextFieldMainActivity)
                    .addComponent(jTextFieldResignedApkPath)))
        );
        jPanelDetailsBarLayout.setVerticalGroup(
            jPanelDetailsBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetailsBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldPackage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldMainActivity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jTextFieldResignedApkPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(76, 76, 76))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldAPKFile, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonBrowse)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jButtonGetDetails)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanelDetailsBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldAPKFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBrowse))
                .addGap(34, 34, 34)
                .addComponent(jButtonGetDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelDetailsBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseActionPerformed
        // TODO add your handling code here:
        
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new MyCustomFilter());
        int option = chooser.showOpenDialog(MainFrame.this);
        if (option == JFileChooser.APPROVE_OPTION) {
          inFile = chooser.getSelectedFile();
          String filelist = "nothing";
          filelist = inFile.getName();
         
          jTextFieldAPKFile.setText("You have choosen : " + filelist);
  
        }
        else {
          jTextFieldAPKFile.setText("You canceled.");
          inFile=null;
        }
        
        
    }//GEN-LAST:event_jButtonBrowseActionPerformed

    private void jButtonGetDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGetDetailsActionPerformed
        // TODO add your handling code here:
        
        if(inFile==null)
        {
            JOptionPane.showMessageDialog(rootPane, "Please Select an apk File");
        }
        else
        {
                
        try {
			String inFileName = "";
				inFileName = inFile.getAbsolutePath();
			
			File outFile = new File(inFileName.replaceAll(".apk", "_debug.apk"));
			// Create a file chooser
			
			        
			String outFileName = outFile.getAbsolutePath();
                         System.out.println("inFileName :"+inFileName+" OutFileName :"+outFileName);
			if (!outFileName.endsWith(".apk"))
				outFileName = outFileName + ".apk";
			String result[] = ResignerLogic.resign(inFileName, outFileName);
			if (result != null) {
				JOptionPane.showMessageDialog(this,
						"apk successfully re-signed");
                                
                                jTextFieldPackage.setText("Package Name :"+result[0]);
                                jTextFieldMainActivity.setText("Main Activity :"+result[1]);
                                jTextFieldResignedApkPath.setText("Debug .apk File Path :"+outFileName);
                                 jPanelDetailsBar.setVisible(true);
			}

		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, "ERROR: " + e.getMessage());
		}
        }
    }//GEN-LAST:event_jButtonGetDetailsActionPerformed
 class MyCustomFilter extends javax.swing.filechooser.FileFilter {
        @Override
        public boolean accept(File file) {
            // Allow only directories, or files with ".txt" extension
            return file.isDirectory() || file.getAbsolutePath().endsWith(".apk");
        }
        @Override
        public String getDescription() {
            // This description will be displayed in the dialog,
            // hard-coded = ugly, should be done via I18N
            return "APK Files (*.apk)";
        }
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBrowse;
    private javax.swing.JButton jButtonGetDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelDetailsBar;
    private javax.swing.JTextField jTextFieldAPKFile;
    private javax.swing.JTextField jTextFieldMainActivity;
    private javax.swing.JTextField jTextFieldPackage;
    private javax.swing.JTextField jTextFieldResignedApkPath;
    // End of variables declaration//GEN-END:variables
}
